Document: pycares
Title: Debian pycares Manual
Author: <insert document author here>
Abstract: This manual describes what pycares is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pycares/pycares.sgml.gz

Format: postscript
Files: /usr/share/doc/pycares/pycares.ps.gz

Format: text
Files: /usr/share/doc/pycares/pycares.text.gz

Format: HTML
Index: /usr/share/doc/pycares/html/index.html
Files: /usr/share/doc/pycares/html/*.html
